/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  WebhookMessageResponse,
  WhatsappSetupWebHookParams
} from '.././model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType , BodyType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const whatsappSetupWebHook = (
    params?: WhatsappSetupWebHookParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/webhook`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getWhatsappSetupWebHookQueryKey = (params?: WhatsappSetupWebHookParams,) => {
    return [`/webhook`, ...(params ? [params]: [])] as const;
    }

    
export const getWhatsappSetupWebHookQueryOptions = <TData = Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError = ErrorType<unknown>>(params?: WhatsappSetupWebHookParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWhatsappSetupWebHookQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof whatsappSetupWebHook>>> = ({ signal }) => whatsappSetupWebHook(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WhatsappSetupWebHookQueryResult = NonNullable<Awaited<ReturnType<typeof whatsappSetupWebHook>>>
export type WhatsappSetupWebHookQueryError = ErrorType<unknown>


export function useWhatsappSetupWebHook<TData = Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError = ErrorType<unknown>>(
 params: undefined |  WhatsappSetupWebHookParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof whatsappSetupWebHook>>,
          TError,
          Awaited<ReturnType<typeof whatsappSetupWebHook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhatsappSetupWebHook<TData = Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError = ErrorType<unknown>>(
 params?: WhatsappSetupWebHookParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof whatsappSetupWebHook>>,
          TError,
          Awaited<ReturnType<typeof whatsappSetupWebHook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWhatsappSetupWebHook<TData = Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError = ErrorType<unknown>>(
 params?: WhatsappSetupWebHookParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useWhatsappSetupWebHook<TData = Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError = ErrorType<unknown>>(
 params?: WhatsappSetupWebHookParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof whatsappSetupWebHook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWhatsappSetupWebHookQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const whatsappReceiveNotifcation = (
    webhookMessageResponse: BodyType<WebhookMessageResponse>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<Blob>(
      {url: `/webhook`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: webhookMessageResponse,
        responseType: 'blob', signal
    },
      options);
    }
  


export const getWhatsappReceiveNotifcationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whatsappReceiveNotifcation>>, TError,{data: BodyType<WebhookMessageResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof whatsappReceiveNotifcation>>, TError,{data: BodyType<WebhookMessageResponse>}, TContext> => {

const mutationKey = ['whatsappReceiveNotifcation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof whatsappReceiveNotifcation>>, {data: BodyType<WebhookMessageResponse>}> = (props) => {
          const {data} = props ?? {};

          return  whatsappReceiveNotifcation(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WhatsappReceiveNotifcationMutationResult = NonNullable<Awaited<ReturnType<typeof whatsappReceiveNotifcation>>>
    export type WhatsappReceiveNotifcationMutationBody = BodyType<WebhookMessageResponse>
    export type WhatsappReceiveNotifcationMutationError = ErrorType<unknown>

    export const useWhatsappReceiveNotifcation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof whatsappReceiveNotifcation>>, TError,{data: BodyType<WebhookMessageResponse>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof whatsappReceiveNotifcation>>,
        TError,
        {data: BodyType<WebhookMessageResponse>},
        TContext
      > => {

      const mutationOptions = getWhatsappReceiveNotifcationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    