/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface Address {
  city?: string;
  country?: string;
  country_code?: string;
  state?: string;
  street?: string;
  type?: string;
  zip?: string;
}
