/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationResult } from './validationResult';
import type { AddressResponsePaginated } from './addressResponsePaginated';

export interface AddressResponsePaginatedServiceResponse {
  /** @nullable */
  errors?: ValidationResult[] | null;
  /** @nullable */
  warnings?: ValidationResult[] | null;
  /** @nullable */
  information?: string[] | null;
  isValid?: boolean;
  content?: AddressResponsePaginated;
}
