/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponseOfCustomerSpecificStatsDtoData } from './apiResponseOfCustomerSpecificStatsDtoData';
import type { ApiResponseOfCustomerSpecificStatsDtoError } from './apiResponseOfCustomerSpecificStatsDtoError';

export interface ApiResponseOfCustomerSpecificStatsDto {
  success?: boolean;
  /** @nullable */
  data?: ApiResponseOfCustomerSpecificStatsDtoData;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiResponseOfCustomerSpecificStatsDtoError;
}
