/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponseOfCheckPaymentResponseData } from './apiResponseOfCheckPaymentResponseData';
import type { ApiResponseOfCheckPaymentResponseError } from './apiResponseOfCheckPaymentResponseError';

export interface ApiResponseOfCheckPaymentResponse {
  success?: boolean;
  /** @nullable */
  data?: ApiResponseOfCheckPaymentResponseData;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiResponseOfCheckPaymentResponseError;
}
