/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { ApiResponseOfUpdateOrderItemTerminalIdsResponseData } from './apiResponseOfUpdateOrderItemTerminalIdsResponseData';
import type { ApiResponseOfUpdateOrderItemTerminalIdsResponseError } from './apiResponseOfUpdateOrderItemTerminalIdsResponseError';

export interface ApiResponseOfUpdateOrderItemTerminalIdsResponse {
  success?: boolean;
  /** @nullable */
  data?: ApiResponseOfUpdateOrderItemTerminalIdsResponseData;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  error?: ApiResponseOfUpdateOrderItemTerminalIdsResponseError;
}
