/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { BaseFilterAdvancedSearch } from './baseFilterAdvancedSearch';
import type { BaseFilterAdvancedFilter } from './baseFilterAdvancedFilter';

export interface BaseFilter {
  /** @nullable */
  advancedSearch?: BaseFilterAdvancedSearch;
  /** @nullable */
  keyword?: string | null;
  /** @nullable */
  advancedFilter?: BaseFilterAdvancedFilter;
}
