/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { BranchSequenceDto } from './branchSequenceDto';

export interface BranchDto {
  id?: number;
  sequenceId?: number;
  code?: number;
  name?: string;
  nameAr?: string;
  /** @nullable */
  description?: string | null;
  sequence?: BranchSequenceDto;
}
