/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { CityRegionDto } from './cityRegionDto';

export interface CityDto {
  id?: number;
  regionId?: number;
  /** @nullable */
  regionNameAr?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nameAr?: string | null;
  latitude?: number;
  longitude?: number;
  mapZoom?: number;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  mobileRegex?: string | null;
  region?: CityRegionDto;
  regionCountry?: CityRegionDto;
}
