/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from './address';
import type { Email } from './email';
import type { Name } from './name';
import type { Org } from './org';
import type { Phone } from './phone';
import type { Url } from './url';

export interface ContactMessage {
  addresses?: Address[];
  birthday?: string;
  emails?: Email[];
  name?: Name;
  org?: Org;
  phones?: Phone[];
  urls?: Url[];
}
