/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface ContractOrderItemDto {
  id?: number;
  /** @nullable */
  subscriptionCode?: number | null;
  /** @nullable */
  subscriptionBundleId?: number | null;
  /** @nullable */
  subscriptionBundleBundleName?: string | null;
  /** @nullable */
  subscriptionBundleBundleNameAr?: string | null;
  /** @nullable */
  subscriptionBundlePrice?: number | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  productName?: string | null;
  /** @nullable */
  productNameAr?: string | null;
  /** @nullable */
  productPrice?: number | null;
  totalPrice?: number;
  qty?: number;
  /** @nullable */
  terminalId?: number | null;
  kitSerialNumber?: string;
  /** @nullable */
  dishSerialNumber?: string | null;
  /** @nullable */
  userTerminalId?: string | null;
  /** @nullable */
  serviceLineNumber?: string | null;
}
