/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { TerminlaKits } from './terminlaKits';

export interface CreateTerminalRequest {
  productId?: number;
  /** @nullable */
  fromAgentId?: number | null;
  /** @nullable */
  fromBranchId?: number | null;
  /** @nullable */
  fromWarehouseId?: number | null;
  /** @nullable */
  refe?: string | null;
  /** @nullable */
  note?: string | null;
  type?: number;
  /** @nullable */
  purchaseDate?: string | null;
  terminlaKits?: TerminlaKits[];
}
