/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterKitDto } from './registerKitDto';

export interface CreateRegisterTerminalRequest {
  customerId?: number;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  agentId?: number | null;
  terminals?: RegisterKitDto[];
  /** @nullable */
  refe?: string | null;
  /** @nullable */
  note?: string | null;
}
