/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateAgentRequest {
  name?: string;
  /** @nullable */
  nameAr?: string | null;
  /** @nullable */
  licenseNo?: string | null;
  countryId?: number;
  regionId?: number;
  cityId?: number;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  telephone?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  vatNo?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  website?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  ownerMobile?: string | null;
  nationalityTypeId?: number;
  /** @nullable */
  ownerNationalId?: string | null;
  /** @nullable */
  contactName?: string | null;
  /** @nullable */
  contactMobile?: string | null;
  /** @nullable */
  contactEmail?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  bankName?: string | null;
  /** @nullable */
  bankRecipentName?: string | null;
  /** @nullable */
  bankAccountNo?: string | null;
  dealingDate?: string;
  paymentMethod?: number;
  status?: number;
}
