/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSubscriptionHistoryRequest {
  subscriptionId?: number;
  action?: number;
  oldPlanId?: number;
  newPlanId?: number;
  oldPlanEndDate?: string;
  oldPlanEndDateId?: number;
  newPlanEndDate?: string;
  oldPlanNewDateId?: number;
  oldStatus?: number;
  newStatus?: number;
  paymentTransactionId?: number;
  changeDate?: string;
}
