/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateStarlinkAddressRequest {
  addressLines?: string[];
  /** @nullable */
  locality?: string | null;
  /** @nullable */
  administrativeArea?: string | null;
  administrativeAreaCode?: string;
  /** @nullable */
  region?: string | null;
  regionCode?: string;
  /** @nullable */
  postalCode?: string | null;
  metadata?: string;
  formattedAddress?: string;
  latitude?: number;
  longitude?: number;
}
