/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface CreateWalletRequest {
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  paymentProviderId?: number | null;
  ownerType?: number;
  balance?: number;
}
