/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemDto } from './orderItemDto';

export interface CreateOrderRequest {
  code?: number;
  customerId?: number;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  warehouseId?: number | null;
  orderDate?: string;
  type?: number;
  status?: number;
  orderItems?: OrderItemDto[];
}
