/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { CustomerDtoGender } from './customerDtoGender';
import type { SubscriptionDto } from './subscriptionDto';
import type { CustomerAttachmentDto } from './customerAttachmentDto';

export interface CustomerDto {
  id?: number;
  customerTypeId?: number;
  /** @nullable */
  customerTypeName?: string | null;
  /** @nullable */
  customerTypeNameAr?: string | null;
  customerFullName?: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  grandFatherName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  gender?: CustomerDtoGender;
  /** @nullable */
  birthDay?: string | null;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  nationality?: string | null;
  /** @nullable */
  nationalityTypeId?: number | null;
  /** @nullable */
  nationalityTypeName?: string | null;
  /** @nullable */
  nationalityTypeNameAr?: string | null;
  /** @nullable */
  nationalityId?: string | null;
  /** @nullable */
  nationalIdIssueDate?: string | null;
  /** @nullable */
  issuePlace?: string | null;
  /** @nullable */
  nationalIdExpiryDate?: string | null;
  mobile?: string;
  /** @nullable */
  email?: string | null;
  countryId?: number;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  countryNameAr?: string | null;
  regionId?: number;
  /** @nullable */
  regionName?: string | null;
  /** @nullable */
  regionNameAr?: string | null;
  cityId?: number;
  /** @nullable */
  cityName?: string | null;
  /** @nullable */
  cityNameAr?: string | null;
  /** @nullable */
  residency?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  filed?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  licesnseType?: string | null;
  /** @nullable */
  licesnseNo?: string | null;
  /** @nullable */
  licenseIssueDate?: string | null;
  /** @nullable */
  licenseIssuePlace?: string | null;
  /** @nullable */
  licenseExpiryDate?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  neighborhood?: string | null;
  /** @nullable */
  nameOfAuthorizedPerson?: string | null;
  /** @nullable */
  titleofAuthorizedPerson?: string | null;
  /** @nullable */
  nationalTypeIdofAuthorizedPerson?: number | null;
  /** @nullable */
  naionalIdofAuthorizedPerson?: string | null;
  /** @nullable */
  mobileOfAuthorizedPerson?: string | null;
  /** @nullable */
  telephone?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  landMark?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  subscriptions?: SubscriptionDto[] | null;
  totalSubscriptions?: number;
  /** @nullable */
  customerAttachments?: CustomerAttachmentDto[] | null;
}
