/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type DataBlockType = typeof DataBlockType[keyof typeof DataBlockType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataBlockType = {
  IncludedWithBaseSubscription: 'IncludedWithBaseSubscription',
  RecurringPerBillingCycle: 'RecurringPerBillingCycle',
  Overage: 'Overage',
  OneTimePurchase: 'OneTimePurchase',
} as const;
