/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { DataUsageOverageLine } from './dataUsageOverageLine';
import type { DataServicePlanDataPoolUsage } from './dataServicePlanDataPoolUsage';
import type { DataServicePlanDataCategoryMapping } from './dataServicePlanDataCategoryMapping';

export interface DataServicePlan {
  /** @nullable */
  isoCurrencyCode?: string | null;
  /** @nullable */
  isMobilePlan?: boolean | null;
  /** @nullable */
  activeFrom?: string | null;
  /** @nullable */
  subscriptionActiveFrom?: string | null;
  /** @nullable */
  subscriptionEndDate?: string | null;
  /** @nullable */
  overageName?: string | null;
  /** @nullable */
  overageDescription?: string | null;
  isOptedIntoOverage?: boolean;
  /** @nullable */
  overageLineDeactivatedDate?: string | null;
  overageLine?: DataUsageOverageLine;
  /** @nullable */
  dataPoolUsage?: DataServicePlanDataPoolUsage;
  productId: string;
  usageLimitGB?: number;
  dataCategoryMapping: DataServicePlanDataCategoryMapping;
}
