/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type ExportWalletTransactionRequestAllOf = {
  /** @nullable */
  walletId?: number | null;
  /** @nullable */
  transactionDate?: string | null;
  /** @nullable */
  transactionDateId?: number | null;
  /** @nullable */
  transactionType?: number | null;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  subscriptionId?: number | null;
  /** @nullable */
  orderId?: number | null;
};
