/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type ExportOrderRequestAllOf = {
  /** @nullable */
  code?: number | null;
  /** @nullable */
  search?: string | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  paymentCode?: number | null;
  /** @nullable */
  customerTypeId?: number | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  orderDate?: string | null;
  /** @nullable */
  orderDateId?: number | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  type?: number | null;
  /** @nullable */
  subscriptionBundleId?: number | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  terminalId?: number | null;
  /** @nullable */
  terminalKit?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  lastModifiedBy?: string | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
};
