/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemDto } from './orderItemDto';

export interface OrderResponse {
  customerId?: number;
  customerFullName?: string;
  orderId?: number;
  /** @nullable */
  paymentCode?: string | null;
  code?: number;
  date?: string;
  total?: number;
  status?: number;
  statusName?: string;
  type?: number;
  typeName?: string;
  orderItems?: OrderItemDto[];
}
