/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderStatus } from './orderStatus';
import type { OrderAttachmentDto } from './orderAttachmentDto';
import type { OrderType } from './orderType';
import type { OrderDtoCustomer } from './orderDtoCustomer';
import type { PaymentTransactionDto } from './paymentTransactionDto';
import type { OrderItemDto } from './orderItemDto';

export interface OrderDto {
  code?: number;
  id?: number;
  customerId?: number;
  /** @nullable */
  customerFirstName?: string | null;
  /** @nullable */
  customerMiddleName?: string | null;
  /** @nullable */
  customerGrandFatherName?: string | null;
  /** @nullable */
  customerFamilyName?: string | null;
  /** @nullable */
  customerCompanyName?: string | null;
  customerFullName?: string;
  customerCustomerTypeId?: number;
  /** @nullable */
  customerCustomerTypeName?: string | null;
  /** @nullable */
  customerCustomerTypeNameAr?: string | null;
  customerCountryId?: number;
  /** @nullable */
  customerCountryName?: string | null;
  /** @nullable */
  customerCountryNameAr?: string | null;
  customerRegionId?: number;
  /** @nullable */
  customerRegionName?: string | null;
  /** @nullable */
  customerRegionNameAr?: string | null;
  customerCityId?: number;
  /** @nullable */
  customerCityName?: string | null;
  /** @nullable */
  customerCityNameAr?: string | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  agentName?: string | null;
  /** @nullable */
  agentNameAr?: string | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  branchName?: string | null;
  /** @nullable */
  branchNameAr?: string | null;
  /** @nullable */
  warehouseId?: number | null;
  /** @nullable */
  warehouseName?: string | null;
  /** @nullable */
  warehouseNameAr?: string | null;
  orderDate?: string;
  /** @nullable */
  createdBy?: string | null;
  orderDateId?: number;
  status?: OrderStatus;
  statusName?: string;
  /** @nullable */
  attachment?: string | null;
  paymentCode?: number;
  /** @nullable */
  orderAttachments?: OrderAttachmentDto[] | null;
  total?: number;
  count?: number;
  type?: OrderType;
  typeName?: string;
  orderItemsExportString?: string;
  /** @nullable */
  customer?: OrderDtoCustomer;
  /** @nullable */
  paymentTransactions?: PaymentTransactionDto[] | null;
  orderItems?: OrderItemDto[];
}
