/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type PaymentMethodStatus = typeof PaymentMethodStatus[keyof typeof PaymentMethodStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentMethodStatus = {
  Sadad: 0,
  Transfer: 1,
  Cash: 2,
} as const;
