/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemDto } from './orderItemDto';
import type { PaymentMethodStatus } from './paymentMethodStatus';
import type { PaymentTransactionStatus } from './paymentTransactionStatus';
import type { KitInfoDto } from './kitInfoDto';

export interface PaymentTransactionDto {
  id?: number;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  orderCode?: number | null;
  /** @nullable */
  orderCustomerId?: number | null;
  /** @nullable */
  orderCustomerFirstName?: string | null;
  /** @nullable */
  orderCustomerMiddleName?: string | null;
  /** @nullable */
  orderCustomerGrandFatherName?: string | null;
  /** @nullable */
  orderCustomerFamilyName?: string | null;
  /** @nullable */
  orderCustomerCompanyName?: string | null;
  /** @nullable */
  orderCustomerFullName?: string | null;
  orderType?: number;
  /** @nullable */
  orderOrderItems?: OrderItemDto[] | null;
  /** @nullable */
  subscriptionId?: number | null;
  /** @nullable */
  subscriptionCode?: number | null;
  /** @nullable */
  subscriptionSubscriptionBundleName?: string | null;
  /** @nullable */
  subscriptionSubscriptionBundleNameAr?: string | null;
  /** @nullable */
  paymentProviderId?: number | null;
  /** @nullable */
  paymentProviderName?: string | null;
  /** @nullable */
  paymentProviderNameAr?: string | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  agentName?: string | null;
  /** @nullable */
  agentNameAr?: string | null;
  /** @nullable */
  paymentProviderTransactionId?: string | null;
  /** @nullable */
  note?: string | null;
  amount?: number;
  paymentDate?: string;
  paymentMethodId?: PaymentMethodStatus;
  paymentCode?: number;
  status?: PaymentTransactionStatus;
  /** @nullable */
  createdBy?: string | null;
  kitInfoExportString?: string;
  /** @nullable */
  kitInfos?: KitInfoDto[] | null;
  saleType?: string;
  orderItemsExportString?: string;
}
