/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemDto } from './orderItemDto';

export interface RegistreDeviceRequest {
  recaptchaToken?: string;
  customerTypeId?: number;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  grandFatherName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  gender?: number | null;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  nationality?: string | null;
  /** @nullable */
  nationalityTypeId?: number | null;
  /** @nullable */
  nationalityId?: string | null;
  /** @nullable */
  nationalIdIssueDate?: string | null;
  /** @nullable */
  issuePlace?: string | null;
  /** @nullable */
  nationalIdExpiryDate?: string | null;
  mobile?: string;
  /** @nullable */
  email?: string | null;
  countryId?: number;
  regionId?: number;
  cityId?: number;
  /** @nullable */
  residency?: string | null;
  /** @nullable */
  companyName?: string | null;
  /** @nullable */
  filed?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  licesnseNo?: string | null;
  /** @nullable */
  licesnseType?: string | null;
  /** @nullable */
  licenseIssueDate?: string | null;
  /** @nullable */
  licenseIssuePlace?: string | null;
  /** @nullable */
  licenseExpiryDate?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  nameOfAuthorizedPerson?: string | null;
  /** @nullable */
  titleofAuthorizedPerson?: string | null;
  /** @nullable */
  nationalTypeIdofAuthorizedPerson?: number | null;
  /** @nullable */
  naionalIdofAuthorizedPerson?: string | null;
  /** @nullable */
  mobileOfAuthorizedPerson?: string | null;
  /** @nullable */
  telephone?: string | null;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  landMark?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  warehouseId?: number | null;
  type?: number;
  status?: number;
  /** @nullable */
  birthDay?: string | null;
  /** @nullable */
  neighborhood?: string | null;
  orderItems?: OrderItemDto[];
}
