/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { RegionCountryDto } from './regionCountryDto';

export interface RegionDto {
  id?: number;
  countryId?: number;
  /** @nullable */
  countryNameAr?: string | null;
  name?: string;
  nameAr?: string;
  latitude?: number;
  longitude?: number;
  mapZoom?: number;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  mobileRegex?: string | null;
  country?: RegionCountryDto;
}
