/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchCountryRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nameAr?: string | null;
  /** @nullable */
  countryCode?: string | null;
};
