/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchStockRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  dateId?: number | null;
  /** @nullable */
  terminalId?: number | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  warehouseId?: number | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  qty?: number | null;
  /** @nullable */
  cost?: number | null;
  /** @nullable */
  costAverage?: number | null;
};
