/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchCustomerRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  middleName?: string | null;
  /** @nullable */
  grandFatherName?: string | null;
  /** @nullable */
  familyName?: string | null;
  /** @nullable */
  customerTypeId?: number | null;
  /** @nullable */
  customerTypeName?: number | null;
  /** @nullable */
  customerTypeNameAr?: number | null;
  /** @nullable */
  nationalityTypeId?: number | null;
  /** @nullable */
  nationalityId?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  nationalSequenceId?: string | null;
  /** @nullable */
  nationalIdQR?: string | null;
  /** @nullable */
  documentNo?: string | null;
  /** @nullable */
  countryId?: number | null;
  /** @nullable */
  countryName?: string | null;
  /** @nullable */
  countryNameAr?: string | null;
  /** @nullable */
  regionId?: number | null;
  /** @nullable */
  regionName?: string | null;
  /** @nullable */
  regionNameAr?: string | null;
  /** @nullable */
  cityId?: number | null;
  /** @nullable */
  cityName?: string | null;
  /** @nullable */
  cityNameAr?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  lastModifiedBy?: string | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  toDate?: string | null;
};
