/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchTerminalRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  productId?: number | null;
  /** @nullable */
  kitSerialNumber?: string | null;
  /** @nullable */
  dishSerialNumber?: string | null;
  /** @nullable */
  refe?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  purchaseDate?: string | null;
  /** @nullable */
  status?: number | null;
  showOnlyAvailableTerminals?: boolean;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  lastModifiedBy?: string | null;
};
