/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchSubscriptionRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  subscriptionBundleId?: number | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  terminalId?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  startDateId?: number | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  endDateId?: number | null;
  /** @nullable */
  renewalDate?: string | null;
  /** @nullable */
  renewalDateId?: number | null;
  /** @nullable */
  renewalType?: number | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  createdBy?: string | null;
  /** @nullable */
  lastModifiedBy?: string | null;
};
