/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SearchTerminalHistoryRequestAllOf = {
  /** @nullable */
  search?: string | null;
  /** @nullable */
  terminalId?: number | null;
  /** @nullable */
  fromDate?: string | null;
  /** @nullable */
  totDate?: string | null;
  /** @nullable */
  eventType?: number | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  fromBranchId?: number | null;
  /** @nullable */
  fromWarehouseId?: number | null;
  /** @nullable */
  fromAgentId?: number | null;
  /** @nullable */
  toBranchId?: number | null;
  /** @nullable */
  toWarehouseId?: number | null;
  /** @nullable */
  toAgentId?: number | null;
  /** @nullable */
  note?: string | null;
};
