/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { DataBlockSummaryResponse } from './dataBlockSummaryResponse';

export interface ServiceLineDataBlocksSummaryResponse {
  /** @nullable */
  recurringBlocksCurrentBillingCycle?: DataBlockSummaryResponse[] | null;
  /** @nullable */
  recurringBlocksNextBillingCycle?: DataBlockSummaryResponse[] | null;
  /** @nullable */
  delayedProductRecurringBlocksNextCycle?: DataBlockSummaryResponse[] | null;
  /** @nullable */
  topUpBlocksOptInPurchase?: DataBlockSummaryResponse[] | null;
  /** @nullable */
  topUpBlocksOneTimePurchase?: DataBlockSummaryResponse[] | null;
}
