/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceLineResponseAviationMetadata } from './serviceLineResponseAviationMetadata';
import type { ServiceLineResponseDataBlocks } from './serviceLineResponseDataBlocks';

export interface ServiceLineResponse {
  addressReferenceId?: string;
  serviceLineNumber?: string;
  /** @nullable */
  nickname?: string | null;
  productReferenceId?: string;
  /** @nullable */
  delayedProductId?: string | null;
  /** @nullable */
  optInProductId?: string | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  endDate?: string | null;
  publicIp?: boolean;
  active?: boolean;
  /** @nullable */
  aviationMetadata?: ServiceLineResponseAviationMetadata;
  /** @nullable */
  dataBlocks?: ServiceLineResponseDataBlocks;
}
