/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { Conversation } from './conversation';
import type { Pricing } from './pricing';

export interface Status {
  id?: string;
  status?: string;
  timestamp?: string;
  recipient_id?: string;
  conversation?: Conversation;
  pricing?: Pricing;
}
