/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export type SubscriptionStatus = typeof SubscriptionStatus[keyof typeof SubscriptionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionStatus = {
  Active: 0,
  Inactive: 1,
  Suspended: 2,
} as const;
