/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePaymentTransactionRequest {
  id?: number;
  /** @nullable */
  orderId?: number | null;
  /** @nullable */
  subscriptionId?: number | null;
  /** @nullable */
  paymentProviderId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  paymentProviderTransactionId?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  amount?: number | null;
  /** @nullable */
  paymentDate?: string | null;
  /** @nullable */
  status?: number | null;
  paymentMethodId?: number;
}
