/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateStarlinkAddressRequest {
  addressReferenceId?: string;
  /** @nullable */
  addressLines?: string[] | null;
  /** @nullable */
  locality?: string | null;
  /** @nullable */
  administrativeArea?: string | null;
  /** @nullable */
  administrativeAreaCode?: string | null;
  /** @nullable */
  region?: string | null;
  /** @nullable */
  regionCode?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  metadata?: string | null;
  /** @nullable */
  formattedAddress?: string | null;
  latitude: number;
  longitude: number;
}
