/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSubscriptionRequest {
  id?: number;
  code?: number;
  /** @nullable */
  subscriptionBundleId?: number | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  terminalId?: number | null;
  /** @nullable */
  startDate?: string | null;
  /** @nullable */
  startDateId?: number | null;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  endDateId?: number | null;
  /** @nullable */
  renewalDate?: string | null;
  /** @nullable */
  renewalDateId?: number | null;
  /** @nullable */
  renewalType?: number | null;
  amount?: number;
  /** @nullable */
  status?: number | null;
}
