/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { OrderItemTerminalResultDto } from './orderItemTerminalResultDto';

export interface UpdateOrderItemTerminalIdsResponse {
  success?: boolean;
  /** @nullable */
  message?: string | null;
  failedItems?: OrderItemTerminalResultDto[];
  processedItems?: OrderItemTerminalResultDto[];
}
