/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCountryRequest {
  id?: number;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nameAr?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  mapZoom?: number | null;
  /** @nullable */
  countryCode?: string | null;
  /** @nullable */
  mobileRegex?: string | null;
}
