/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateSubscriptionHistoryRequest {
  id?: number;
  /** @nullable */
  subscriptionId?: number | null;
  /** @nullable */
  action?: number | null;
  /** @nullable */
  oldPlanId?: number | null;
  /** @nullable */
  newPlanId?: number | null;
  /** @nullable */
  oldPlanEndDate?: string | null;
  /** @nullable */
  oldPlanEndDateId?: number | null;
  /** @nullable */
  newPlanEndDate?: string | null;
  /** @nullable */
  newPlanStartDate?: string | null;
  /** @nullable */
  oldPlanNewDateId?: number | null;
  /** @nullable */
  oldStatus?: number | null;
  /** @nullable */
  newStatus?: number | null;
  /** @nullable */
  paymentTransactionId?: number | null;
  /** @nullable */
  changeDate?: string | null;
}
