/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateRegisterTerminalRequest {
  id?: number;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  kitSerialNumber?: string | null;
  /** @nullable */
  dishSerialNumber?: string | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  userTerminalId?: string | null;
  /** @nullable */
  refe?: string | null;
  /** @nullable */
  note?: string | null;
}
