/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCustomerAttachmentRequestAttachment } from './updateCustomerAttachmentRequestAttachment';

export interface UpdateCustomerAttachmentRequest {
  id?: number;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  name?: string | null;
  deleteCurrentAttachment?: boolean;
  /** @nullable */
  attachment?: UpdateCustomerAttachmentRequestAttachment;
  /** @nullable */
  description?: string | null;
}
