/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { UserTerminalDtoConfigId } from './userTerminalDtoConfigId';
import type { UserTerminalDtoRoutersItem } from './userTerminalDtoRoutersItem';

export interface UserTerminalDto {
  /** @nullable */
  locationNickname?: string | null;
  /** @nullable */
  locationFormattedAddress?: string | null;
  /** @nullable */
  userTerminalId?: string | null;
  /** @nullable */
  serialNumber?: string | null;
  /** @nullable */
  dishSerialNumber?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  active?: boolean | null;
  /** @nullable */
  configId?: UserTerminalDtoConfigId;
  /** @nullable */
  nickname?: string | null;
  /** @nullable */
  lastConnected?: string | null;
  /** @nullable */
  lastDisconnected?: string | null;
  /** @nullable */
  routers?: UserTerminalDtoRoutersItem[] | null;
  /** @nullable */
  isOffline?: boolean | null;
}
