/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  id?: number;
  identityId?: string;
  firstName?: string;
  lastName?: string;
  type?: number;
  /** @nullable */
  typeName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  mobile?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  branchId?: number | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  branchName?: string | null;
  /** @nullable */
  branchNameAr?: string | null;
  /** @nullable */
  agentName?: string | null;
  /** @nullable */
  agentNameAr?: string | null;
  userName?: string;
  /** @nullable */
  role?: string | null;
  isAdmin?: boolean;
}
