/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */
import type { Metadata } from './metadata';
import type { Contact } from './contact';
import type { Message } from './message';
import type { Status } from './status';

export interface Value {
  messaging_product?: string;
  metadata?: Metadata;
  /** @nullable */
  contacts?: Contact[] | null;
  /** @nullable */
  messages?: Message[] | null;
  /** @nullable */
  statuses?: Status[] | null;
}
