/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface WalletTransactionDto {
  id?: number;
  /** @nullable */
  walletId?: number | null;
  /** @nullable */
  walletCustomerId?: number | null;
  /** @nullable */
  walletCustomerFirstName?: string | null;
  /** @nullable */
  walletCustomerMiddleName?: string | null;
  /** @nullable */
  walletCustomerGrandFatherName?: string | null;
  /** @nullable */
  walletCustomerFamilyName?: string | null;
  transactionDate?: string;
  transactionDateId?: number;
  transactionType?: number;
  amount?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  subscriptionId?: number | null;
  /** @nullable */
  orderId?: number | null;
}
