/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * .NET 7 WebAPI - Clean Architecture
 * Clean Architecture Template for .NET 7 WebApi built with Multitenancy Support.
 * OpenAPI spec version: 1.0.0
 */

export interface WalletDto {
  id?: number;
  /** @nullable */
  customerId?: number | null;
  /** @nullable */
  customerFirstName?: string | null;
  /** @nullable */
  customerMiddleName?: string | null;
  /** @nullable */
  customerGrandFatherName?: string | null;
  /** @nullable */
  customerFamilyName?: string | null;
  /** @nullable */
  agentId?: number | null;
  /** @nullable */
  agentName?: string | null;
  /** @nullable */
  agentNameAr?: string | null;
  /** @nullable */
  paymentProviderId?: number | null;
  /** @nullable */
  paymentProviderName?: string | null;
  /** @nullable */
  paymentProviderNameAr?: string | null;
  ownerType?: number;
  balance?: number;
}
